name: Upload to NuGet, Update Changelog, and Publish Docs

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest
    environment: Nuget
    steps:

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.x' # Adjust according to your target .NET version

      - name: Restore dependencies
        run: dotnet restore

      - name: Install DocFX
        run: choco install docfx -y

      - name: Build documentation with DocFX
        run: docfx docfx.json

      - name: Run upload script
        run: ./upload.ps1
        shell: pwsh
        env:
          NugetKey: ${{ secrets.KEY }}  # Pass the NuGet API key secret to the script

      - name: Deploy documentation to GitHub Pages
        if: success()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: _site
